name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Scaleway Object Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_ID }} --exclude '.git/*' --exclude '.github/*' --exclude '.DS_Store' --exclude 'README.md' --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: 'https://s3.fr-par.scw.cloud'
          AWS_DEFAULT_REGION: 'fr-par'
